// <auto-generated />
namespace PhotoGallery.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_to_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_to_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202106161347030_FK_to_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
